# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Server
destination:      _gh_pages
host:             127.0.0.1
port:             3001
baseurl:          /GRNsight
encoding:         UTF-8

# SEO metadata
title: GRNsight
description: GRNsight is an open source web application and service for visualizing models of small- to medium-scale gene regulatory networks.
url: http://dondi.github.io
# author is not set, because it turns out to be Twitter-specific
logo: /assets/images/GRNsight_logo_20140710_main_resized.jpg
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
